apiVersion: v1
kind: Service
metadata:
  name: {{ template "thriftserver-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.ThriftServer.Component }}"
spec:
  ports:
  - port: {{ .Values.ThriftServer.ServicePort }}
    targetPort: {{ .Values.ThriftServer.ContainerPort }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.ThriftServer.Component }}"
  type: {{ .Values.ThriftServer.ServiceType }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "thriftserver-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.ThriftServer.Component }}"
spec:
  replicas: {{ default 1 .Values.ThriftServer.Replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.ThriftServer.Component }}"
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.ThriftServer.Component }}"
    spec:
      serviceName: {{ template "thriftserver-fullname" . }}
      containers:
        - image: "{{ .Values.ThriftServer.Image }}"
          imagePullPolicy: "{{ .Values.ThriftServer.ImagePullPolicy }}"
          name: {{ template "thriftserver-fullname" . }}
          ports:
            - containerPort: {{ .Values.ThriftServer.ContainerPort }}
          resources:
            requests:
              cpu: "{{ .Values.ThriftServer.Cpu }}"
              memory: "{{ .Values.ThriftServer.Memory }}"
          env:
            - name: HIVE_CONF_DIR
              value: /hive_conf
            - name: METASTORE_CONF_DIR
              value: /hive_conf

          volumeMounts:
            - name: hive-vol
              mountPath: /hive_conf

      volumes:
        - name: hive-vol
          secret:
            secretName: {{ .Values.Hive.SecretName }}



