apiVersion: v1
kind: Service
metadata:
  name: {{ template "worker-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  ports:
  - port: {{ .Values.Worker.ServicePort }}
    targetPort: {{ .Values.Worker.ContainerPort }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
  type: {{ .Values.Worker.ServiceType }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "worker-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
spec:
  replicas: {{ default 1 .Values.Worker.Replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
    spec:
      serviceName: {{ template "worker-fullname" . }}
      containers:
        - image: "{{ .Values.Worker.Image }}"
          imagePullPolicy: "{{ .Values.Worker.ImagePullPolicy }}"
          name: {{ template "worker-fullname" . }}
          ports:
            - containerPort: {{ .Values.WebUi.ContainerPort }}
          resources:
            requests:
              cpu: "{{ .Values.Worker.Cpu }}"
              memory: "{{ .Values.Worker.Memory }}"
          env:
            - name: SPARK_HOME
              value: /spark
            - name: SPARK_MASTER
              value: "spark://{{ template "master-fullname" . }}:{{ .Values.Master.ServicePort }}"
            - name: INIT_DAEMON_STEP
              value: setup_spark
            - name: SPARK_MASTER_HOST
              value: {{ template "master-fullname" . }}
            - name: SPARK_DAEMON_MEMORY
              value: {{ default "1g" .Values.Worker.DaemonMemory | quote }}
            - name: SPARK_WORKER_MEMORY
              value: {{ default "1g" .Values.Worker.WorkerMemory | quote }}
            - name: SPARK_WORKER_WEBUI_PORT
              value: {{ .Values.WebUi.ContainerPort | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.Aws.SecretName }}
                  key: aws_secret_access_key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.Aws.SecretName }}
                  key: aws_access_key_id
            - name: PYSPARK_PYTHON
              value: {{ .Values.Pyspark.PythonVersion }} 
            - name: PYSPARK_DRIVER_PYTHON
              value: {{ .Values.Pyspark.PythonVersion }} 
          volumeMounts:
            - name: hadoop-vol
              mountPath: /hadoop
            - name: gcs-creds-vol
              mountPath: /gcs

      volumes:
        - name: hadoop-vol
          secret:
            secretName: {{ .Values.Hadoop.SecretName }}
        - name: gcs-creds-vol
          secret:
            secretName: {{ .Values.Gcs.SecretName }}


