# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Hive:
  SecretName: dan-hive-metastore-site

Hadoop:
  SecretName: dan-hadoop-core-site

Gcs:
  SecretName: dan-gcs-key

ThriftServer:
  Name: hive-metastore
  Image: davetuner/hive-metastore:3.0.0
  ImagePullPolicy: Always
  Replicas: 1
  Component: "hive-metastore"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 9083
  ContainerPort: 9083
  ServiceType: ClusterIP
  Autoscaling:
    Enabled: true
  ReplicasMax: 10
  CpuTargetPercentage: 50
